/**
 * This class is screen of equipaments reservations change generated by swing
 */
package view.reservasEquipamentos;

import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.ReservaEquipamentoProfessor;
import exception.ClienteException;
import exception.PatrimonyException;
import exception.ReservaException;

public class AlterarReservaEquipamentoView extends ReservaEquipamentoView {

    int index; // Index of reservation
    ReservaEquipamentoProfessor reserva; // Object of reservation that going to change

    private void resetComponents() {
        this.reservarButton.setText("Alterar");
        this.reservarButton.setName("AlterarButton");
        this.cpfLabel.setEnabled(false);
        this.cpfTextField.setBackground(new Color(200, 208, 254));
        this.cpfTextField.setEditable(false);
        this.horaTextField.setText(reserva.getHora());
        this.dataTextField.setText(reserva.getData());
        this.professorTextArea.setText(reserva.getProfessor().toString());
    }

    /**
     * 
     * @param parent
     * @param modal
     * @param index
     * @param mes
     * @throws SQLException
     * @throws PatrimonyException
     * @throws PatrimonyException
     * @throws ClienteException
     * @throws ReservaException
     */
    public AlterarReservaEquipamentoView(Frame parent, boolean modal, int index, int mes) throws SQLException, PatrimonyException,
            PatrimonyException, ClienteException, ReservaException {
        super(parent, modal);
        this.index = index;
        reserva = this.instanceProf.getReservasMes(mes).get(index);
        resetComponents();
    }

    /**
     * 
     * @exception Rerserve null or Database null
     */
    @Override protected void reservarProfessor() {
        try {

            instanceProf.alterar(null, reserva);
            JOptionPane.showMessageDialog(this, "Reserva alterada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE, null);
            this.setVisible(false);
        } catch (ReservaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        }
    }

}
