/**
 * This class is screen of to make equipaments reservations generated by swing
 */
package view.reservasEquipamentos;

import java.awt.Frame;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import model.Equipamento;
import exception.ClienteException;
import exception.PatrimonyException;
import exception.ReservaException;

public class FazerReservaEquipamentoView extends ReservaEquipamentoView {

    Equipamento equipamento; // Object of equipament's reservation that going to create

    /**
     * 
     * @param parent
     * @param modal
     * @param e
     * @param data
     * @throws SQLException
     * @throws PatrimonyException
     * @throws PatrimonyException
     * @throws ClienteException
     * @throws ReservaException
     */
    public FazerReservaEquipamentoView(Frame parent, boolean modal, Equipamento e, String data) throws SQLException,
            PatrimonyException, PatrimonyException, ClienteException, ReservaException {
        super(parent, modal);
        this.equipamento = e;
        this.dataTextField.setText(data);
        this.equipamentoTextArea.setText(e.toString());
    }

    /**
     * 
     * @exception Rerserve null or Database null
     * 
     * (non-Javadoc)
     * @see view.reservasEquipamentos.ReservaEquipamentoView#reservarProfessor()
     */
    @Override protected void reservarProfessor() {
        try {

            instanceProf.inserir(equipamento, prof, this.dataTextField.getText(), this.horaTextField.getText());

            JOptionPane.showMessageDialog(this, "Reserva feita com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE, null);

            this.setVisible(false);
        } catch (ReservaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        }
    }

}
