/**
 * This class is a screen of to change teacher's reserve generated by swing
 */
package view.reservasSalas;

import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;

import javax.swing.JOptionPane;

<<<<<<< HEAD
import model.ReserveClassroomForProfessor;
import exception.ClientException;
import exception.PatrimonyException;
import exception.ReserveException;
=======
import model.ReservaSalaProfessor;
import exception.ClienteException;
import exception.PatrimonyException;
import exception.ReservaException;
>>>>>>> devel

public class AlterarReservaProfSalaView extends ReservaSalaView {

<<<<<<< HEAD
    int index;
    ReserveClassroomForProfessor reservaProfessor;
=======
    int index; // Index of reserve
    ReservaSalaProfessor reservaProfessor; // Object of teacher's reserve
>>>>>>> devel

    /**
     * Clean all components
     */
    private void resetComponents() {
        this.reservarButton.setText("Alterar");
        this.reservarButton.setName("AlterarButton");
        this.professorRadioButton.setSelected(true);
        this.cpfLabel.setEnabled(false);
        professorRadioButtonAction();
    }

    /**
     * 
     * @param parent
     * @param modal
     * @param index
     * @param data
     * @throws SQLException
     * @throws PatrimonyException
     * @throws PatrimonyException
     * @throws ClienteException
     * @throws ReservaException
     */
    public AlterarReservaProfSalaView(Frame parent, boolean modal, int index, String data) throws SQLException,
<<<<<<< HEAD
            PatrimonyException, PatrimonyException, ClientException, ReserveException {
=======
            PatrimonyException, PatrimonyException, ClienteException, ReservaException {
>>>>>>> devel
        super(parent, modal);
        this.setName("AlterarReservaSalaView");
        this.reservaProfessor = instanceProf.searchForDate(data).get(index);
        resetComponents();

    }

    /**
     * @exception Reserve is null or Database is null or NullPointer is null
     *
     * (non-Javadoc)
     * @see view.reservasSalas.ReservaSalaView#reservarProfessor()
     */
    @Override protected void reservarProfessor() {
        try {
            instanceProf.update(this.finalidadeTextField.getText(), reservaProfessor);

            JOptionPane.showMessageDialog(this, "Reserva alterada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE, null);

            this.setVisible(false);
        } catch (ReserveException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        }
    }

    /*
     * (non-Javadoc)
     * @see view.reservasSalas.ReservaSalaView#professorRadioButtonAction()
     */
    @Override protected void professorRadioButtonAction() {
        Color blue = new Color(200, 208, 254);
        this.instanceAluno = null;
        this.alunoRadioButton.setEnabled(false);
        this.cpfTextField.setBackground(blue);
        this.cpfTextField.setEditable(false);
        this.qntCadeirasReservadasTextField.setEditable(true);
        this.qntCadeirasReservadasTextField.setBackground(Color.white);
        this.horaTextField.setBackground(blue);
        this.horaTextField.setEditable(false);
        this.horaTextField.setText(reservaProfessor.getHour());
        this.alunoTextArea.setText(reservaProfessor.getProfessor().toString());
<<<<<<< HEAD
        this.salaTextArea.setText(reservaProfessor.getClassroom().toString());
        this.dataTextField.setText(reservaProfessor.getDate());
        this.qntCadeirasTxtField.setText(reservaProfessor.getClassroom().getCapacity());
        this.qntCadeirasReservadasTextField.setText(reservaProfessor.getClassroom().getCapacity());
=======
        this.salaTextArea.setText(reservaProfessor.getSala().toString());
        this.dataTextField.setText(reservaProfessor.getData());
        this.qntCadeirasTxtField.setText(reservaProfessor.getSala().getCapacity());
        this.qntCadeirasReservadasTextField.setText(reservaProfessor.getSala().getCapacity());
>>>>>>> devel
        this.qntCadeirasReservadasTextField.setBackground(blue);
        this.qntCadeirasReservadasTextField.setEditable(false);
        this.finalidadeTextField.setText(reservaProfessor.getFinality());
        this.verificarCadeiraButton.setEnabled(false);
    }

    /*
     * (non-Javadoc)
     * @see view.reservasSalas.ReservaSalaView#alunoRadioButtonAction()
     */
    @Override protected void alunoRadioButtonAction() {

    }

    /*
     * (non-Javadoc)
     * @see view.reservasSalas.ReservaSalaView#reservarAluno()
     */
    @Override protected void reservarAluno() {

    }

    /*
     * (non-Javadoc)
     * @see view.reservasSalas.ReservaSalaView#verificarAction()
     */
    @Override protected void verificarAction() {
       
    }
}
