/**
 * This class is screen of equipaments reservations change generated by swing
 */
package view.reservasEquipamentos;

import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.ReservaEquipamentoProfessor;
import exception.ClienteException;
import exception.PatrimonyException;
import exception.ReservaException;

<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ChangeReservationEquipamentView.java
/**
 * 
 * @author Parley  

 */
public class ChangeReservationEquipamentView extends ReservationEquipmentView {

    int index;
    ReservaEquipamentoProfessor reservation;
=======
public class AlterarReservaEquipamentoView extends ReservaEquipamentoView {

    int index; // Index of reservation
    ReservaEquipamentoProfessor reserva; // Object of reservation that going to change
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/AlterarReservaEquipamentoView.java

    private void resetComponents() {
        this.reservationButton.setText("Alterar");
        this.reservationButton.setName("AlterarButton");
        this.cpfLabel.setEnabled(false);
        this.cpfTextField.setBackground(new Color(200, 208, 254));
        this.cpfTextField.setEditable(false);
        this.timeTextField.setText(reservation.getHora());
        this.dateTextField.setText(reservation.getData());
        this.teacherTextArea.setText(reservation.getProfessor().toString());
    }

<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ChangeReservationEquipamentView.java
    public ChangeReservationEquipamentView(Frame parent, boolean modal, int index, int mes) throws SQLException, PatrimonioException,
            PatrimonioException, ClienteException, ReservaException {
=======
    /**
     * 
     * @param parent
     * @param modal
     * @param index
     * @param mes
     * @throws SQLException
     * @throws PatrimonyException
     * @throws PatrimonyException
     * @throws ClienteException
     * @throws ReservaException
     */
    public AlterarReservaEquipamentoView(Frame parent, boolean modal, int index, int mes) throws SQLException, PatrimonyException,
            PatrimonyException, ClienteException, ReservaException {
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/AlterarReservaEquipamentoView.java
        super(parent, modal);
        this.index = index;
        reservation = this.instanceProf.getReservasMes(mes).get(index);
        resetComponents();
    }

<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ChangeReservationEquipamentView.java
    @Override protected void reservationTeacher() {
=======
    /**
     * 
     * @exception Rerserve null or Database null
     *
     * (non-Javadoc)
     * @see view.reservasEquipamentos.ReservaEquipamentoView#reservarProfessor()
     */
    @Override protected void reservarProfessor() {
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/AlterarReservaEquipamentoView.java
        try {

            instanceProf.alterar(null, reservation);
            JOptionPane.showMessageDialog(this, "Reserva alterada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE, null);
            this.setVisible(false);
        } catch (ReservaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        }
    }

}
