/**
 * This class is main screen of equipaments reservations generated by swing
 */
package view.reservasEquipamentos;

import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JOptionPane;

import model.Professor;
import control.ManterProfessor;
import control.ManterResEquipamentoProfessor;
import exception.ClienteException;
import exception.PatrimonyException;
import exception.ReservaException;

public abstract class ReservationEquipmentView extends javax.swing.JDialog {

    protected ManterResEquipamentoProfessor instanceProf; // Object of professor's reservation
    protected Professor prof; // Object of professor

<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ReservationEquipmentView.java
    public ReservationEquipmentView(java.awt.Frame parent, boolean modal) throws SQLException, PatrimonioException,
            PatrimonioException, ClienteException, ReservaException {
=======
    public ReservaEquipamentoView(java.awt.Frame parent, boolean modal) throws SQLException, PatrimonyException,
            PatrimonyException, ClienteException, ReservaException {
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/ReservaEquipamentoView.java
        super(parent, modal);
        this.instanceProf = ManterResEquipamentoProfessor.getInstance();

        initComponents();
    }

    abstract protected void reservationTeacher();

<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ReservationEquipmentView.java
    protected void getTeacher() {
=======
    /**
     * 
     * @exception Client null or Database null or NullPoiner null
     */
    protected void getProfessor() {
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/ReservaEquipamentoView.java
        try {
            Vector<Professor> teacher = ManterProfessor.getInstance().buscarCpf(this.cpfTextField.getText());
            if (teacher.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Professor nao Cadastrado."
                        + " Digite o CPF correto ou cadastre o teacher desejado", "Erro", JOptionPane.ERROR_MESSAGE, null);
                return;
            }
            this.prof = teacher.firstElement();
            this.teacherTextArea.setText(teacher.firstElement().toString());
        } catch (ClienteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") // <editor-fold defaultstate="collapsed"
                                  // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ReservationEquipmentView.java
        studentTeacherbuttonGroup = new javax.swing.ButtonGroup();
        equipmentLabel = new javax.swing.JLabel();
        teacherLabel = new javax.swing.JLabel();
=======
    	/*
    	 * All components of screen
    	 */
        alunoProfbuttonGroup = new javax.swing.ButtonGroup();
        equipamentoLabel = new javax.swing.JLabel();
        professorLabel = new javax.swing.JLabel();
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/ReservaEquipamentoView.java
        cpfLabel = new javax.swing.JLabel();
        cpfTextField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        reservationButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        equipmentTextArea = new javax.swing.JTextArea();
        dateTextField = new javax.swing.JTextField();
        findCpfButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ReservaPatrimonio");
        setName("ReservaPatrimonio"); // NOI18N
        setResizable(false);

        equipmentLabel.setText("Equipamento:");
        equipmentLabel.setName("EquipamentoLabel"); // NOI18N

        teacherLabel.setText("Professor:");
        teacherLabel.setName("ProfessorLabel"); // NOI18N

        cpfLabel.setText("Digite o CPF desejado :");
        cpfLabel.setName("CpfLabel"); // NOI18N

        cpfTextField.setName("CPF"); // NOI18N
        cpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextFieldActionPerformed(evt);
            }
        });

        dateLabel.setText("Data: ");

        timeLabel.setText("Hora: ");
        timeLabel.setName("HoraLabel"); // NOI18N

        timeTextField.setName("Hora"); // NOI18N

        reservationButton.setText("Reservar");
        reservationButton.setName("Reservar"); // NOI18N
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.setName("Cancelar"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        teacherTextArea.setEditable(false);
        teacherTextArea.setBackground(new java.awt.Color(200, 208, 254));
        teacherTextArea.setColumns(20);
        teacherTextArea.setRows(5);
        teacherTextArea.setName("ProfessorTextArea"); // NOI18N
        jScrollPane1.setViewportView(teacherTextArea);

        equipmentTextArea.setEditable(false);
        equipmentTextArea.setBackground(new java.awt.Color(200, 208, 254));
        equipmentTextArea.setColumns(20);
        equipmentTextArea.setRows(5);
        equipmentTextArea.setName("EquipamentoTextArea"); // NOI18N
        jScrollPane2.setViewportView(equipmentTextArea);

        dateTextField.setEditable(false);
        dateTextField.setBackground(new java.awt.Color(200, 208, 254));
        dateTextField.setName("DiaTextField"); // NOI18N

        findCpfButton.setText("Buscar CPF");
        findCpfButton.setName("BuscarCpfButton"); // NOI18N
        findCpfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCpfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(199, 199, 199)
                                                                .addComponent(reservationButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 82,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cancelButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 81,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(cpfLabel)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(
                                                                                                        cpfTextField,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        164,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(findCpfButton)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addGroup(
                                                                                                        layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        teacherLabel)
                                                                                                                .addComponent(
                                                                                                                        equipmentLabel,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        81,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(
                                                                                                        layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        jScrollPane1)
                                                                                                                .addComponent(
                                                                                                                        jScrollPane2,
                                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING))))
                                                                .addContainerGap())
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(dateLabel)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(dateTextField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(timeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(timeTextField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(findCpfButton))
                        .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup().addGap(51, 51, 51).addComponent(teacherLabel))
                                        .addGroup(
                                                layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(equipmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateTextField)
                                        .addComponent(timeLabel)
                                        .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void cpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cpfTextFieldActionPerformed
        String name = this.cpfTextField.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum CPF digitado", "Erro", JOptionPane.ERROR_MESSAGE, null);
        } else {
            getTeacher();
        }
    } // GEN-LAST:event_cpfTextFieldActionPerformed

<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ReservationEquipmentView.java
    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_reservationButtonActionPerformed
        reservationTeacher();
    }// GEN-LAST:event_reservationButtonActionPerformed
=======
    private void reservarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_reservarButtonActionPerformed
        reservarProfessor();
    } // GEN-LAST:event_reservarButtonActionPerformed
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/ReservaEquipamentoView.java

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ReservationEquipmentView.java
    }// GEN-LAST:event_cancelButtonActionPerformed
=======
    } // GEN-LAST:event_cancelarButtonActionPerformed
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/ReservaEquipamentoView.java

    private void findCpfButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findCpfButtonActionPerformed
        cpfTextFieldActionPerformed(evt);
<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ReservationEquipmentView.java
    }// GEN-LAST:event_findCpfButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup studentTeacherbuttonGroup;
    private javax.swing.JButton findCpfButton;
    protected javax.swing.JButton cancelButton;
=======
    } // GEN-LAST:event_buscarCpfButtonActionPerformed

    /*
     *  Variables declaration - do not modify | GEN-BEGIN:variables
     */
    private javax.swing.ButtonGroup alunoProfbuttonGroup;
    private javax.swing.JButton buscarCpfButton;
    protected javax.swing.JButton cancelarButton;
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/ReservaEquipamentoView.java
    protected javax.swing.JLabel cpfLabel;
    protected javax.swing.JTextField cpfTextField;
    protected javax.swing.JLabel dateLabel;
    protected javax.swing.JTextField dateTextField;
    protected javax.swing.JLabel equipmentLabel;
    protected javax.swing.JTextArea equipmentTextArea;
    protected javax.swing.JLabel timeLabel;
    protected javax.swing.JTextField timeTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
<<<<<<< HEAD:sisres/src/view/reservasEquipamentos/ReservationEquipmentView.java
    protected javax.swing.JLabel teacherLabel;
    protected javax.swing.JTextArea teacherTextArea;
    protected javax.swing.JButton reservationButton;
    // End of variables declaration//GEN-END:variables
=======
    protected javax.swing.JLabel professorLabel;
    protected javax.swing.JTextArea professorTextArea;
    protected javax.swing.JButton reservarButton;
    /*
     *  End of variables declaration//GEN-END:variables
     */
>>>>>>> 7dc6155feb316d34c05aba94bb91558233b9184c:sisres/Codigo/src/view/reservasEquipamentos/ReservaEquipamentoView.java
}
